### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by abdoun** [Spansky/apache-and-letsencrypt#1]
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing. 

pull access denied for lets-encrypt-apache, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Spansky** [comment]
Hi abdoun, you will get this error message when you try to `docker-compose up` the images. You need to first build the mentioned docker image via `docker build -t lets-encrypt-apache .` Then it should work.

**Comment by abdoun** [comment]
I have just used docker build -t .....

**Comment by Spansky** [comment]
I will try to reproduce it. One moment...

**Comment by Spansky** [comment]
![screenshot docker build](https://user-images.githubusercontent.com/5704072/96452713-007df000-124c-11eb-8af7-1a536878a83d.png)

^^looks good. Can you attach a screenshot, when you try that?

**Comment by abdoun** [comment]
I am sorry because I have deleted the project and treid to build the another with another way

**Comment by Spansky** [comment]
Good to hear that. However, I think I can make the repo more failsafe by adding the build context to the docker-compose files. 👍
